### ISSUE TITLE
.chath cannot write as gm in the horde Chat is only seen by gm but not by player

### ISSUE THREAD

**Issue by Selyria** [wizzymore/mod_world_chat#1]
Hello first of all amazing thanks for the great module

I tested it and it's working out. 

Only if I want to write from GM Alliance in Horde Worldchat nobody sees it only those who have the Gm on see it but normal players don't. 

Commands .chath cannot write as gm in the horde Chat is only seen by gm but not by player
Commands .chata cannot write as gm in the alliance Chat is only seen by Gm but not by the player.

I'm not sure if I understand something wrong but if I understood it right you should be able to write gm of alliance in the Horde chat and it should be readable by the Horde players.

AzerothCore rev. 9eb6e9a77760+ 2019-04-05 00:58:08 +0000 (master branch) (Win64, Release)

**Comment by wizzymore** [comment]
Sorry for me not answearing to your issue, i've taken a long pause from the project but now i am back. I will fix this as soon as possible!
Thanks for sharing the issue with me.
