### ISSUE TITLE
Can not set different styles based on gm level.

### ISSUE THREAD

**Issue by TheOneLeeT** [wizzymore/mod_world_chat#9]
All gm (even if I have 9 on my common.h) have same "template" when they type in world chat.

Wanted to add a custom template for each gm lvl.

Few  examples, for gm 9 It should be
 |TInterface/CHATFRAME/UI-CHATICON-BLIZZ:13:13:0:-1|t|cffFF0000[Owner] + char + name + message

or lvl 7: |TInterface/CHATFRAME/UI-CHATICON-BLIZZ:13:13:0:-1|t|cffFF0000[GM+] + char + name + message

and so on...

I added my levels to 
/* Ranks */
std::string world_chat_GM_RANKS[11] =
{
    "Player",
    "V.I.P",
    "Moderator",
    "Trial GM",
    "GM",
    "Dev",
    "Dev+",
    "GM+",
    "Co-Owner",
    "Owner",
    "Console",
};
Based on 
SEC_PLAYER = 0, //Player
SEC_VIP = 1, //VIP
SEC_MODERATOR = 2, //Used for Trial GM
SEC_GAMEMASTER = 3, //Used for GM  (TRIAL GM)
SEC_ADMINISTRATOR = 4, //used for Admin  (FULL GM)
SEC_DEV = 5, //Developer
SEC_HD = 6, //Head Developer
SEC_HA = 7, //Head ADmin
SEC_CO = 8, //Co-Owner
SEC_O = 9, //Owner
SEC_CONSOLE = 10, //Console   

But nothing happens...

**Comment by wizzymore** [comment]
Answered on AC
